---
title: "CryptoData"
author: "yogesh sahu"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#changing or saving the data 
setwd("C:/Users/44776/Documents/GitHub/CryptoDataFetcher/CryptoDataFetcher2.0")
```
```{r}
library(crypto2)
```
```{r Library, include=FALSE}
library(prophet)
library(tidyverse)
library(crypto2)
```


```{r}
# Get Data from CoinMarketCap
coin_list_all <- crypto_list(only_active = TRUE)
```

```{r}
coin_list_1000 <- head(coin_list_all[order(coin_list_all$rank), ], 10116)

```


```{r}
# Define the file name and path for the output CSV file
output_file_path <- paste0(getwd(), "/Top_1000_Cryptocurrencies.csv")

# Write the data to a CSV file in the working directory
write.csv(coin_list_1000, output_file_path, row.names = FALSE)

# Optional: Message to confirm file has been written
message(paste("The CSV file has been created at:", output_file_path))
```

```{r}
crypto_hist <- crypto_history(coin_list = coin_list_1000,
                              convert = "USD", # change to USD or other currency if desired
                              limit = 1000,
                              sleep = 1)
```

```{r}
# Check the structure to confirm new order
print(head(crypto_hist))
```




```{r}

# Load necessary libraries
library(dplyr)
library(lubridate)

# Assuming 'crypto_hist' is your dataset
# Parse datetime columns if they are not already in datetime format
crypto_hist <- crypto_hist %>%
  mutate(
    time_open = ymd_hms(time_open),
    time_close = ymd_hms(time_close),
    time_high = ymd_hms(time_high),
    time_low = ymd_hms(time_low)
  )

# Extract date and time components
crypto_hist <- crypto_hist %>%
  mutate(
    date = as.Date(time_close),
    time_open = format(time_open, "%H:%M:%S"),
    time_close = format(time_close, "%H:%M:%S"),
    time_high = format(time_high, "%H:%M:%S"),
    time_low = format(time_low, "%H:%M:%S")
  )

# Check the first few rows to confirm changes
print(head(crypto_hist))

```

```{r}

# Drop the specified columns
crypto_hist <- crypto_hist %>%
  select(
    -timestamp,
    -time_high,
    -time_low,
    -time_open,
    -time_close,
    -timestamp,
    -time_close,
    -high,
    -low,
    -name,
    -slug,
    -ref_cur,
    -volume
  )

symbols_to_remove <- c("BabyDoge", "BIFI", "BRISE", "CTK", "KISHU", "PIT", "QUACK", "SHPING")
library(dplyr)

# Assuming your dataframe is named crypto_hist and the symbol column is named 'symbol'
crypto_hist <- crypto_hist %>%
  filter(!symbol %in% symbols_to_remove)

```

```{r}
# Write the filtered data to a CSV file
write.csv(crypto_hist, "crypto_hist.csv", row.names = FALSE)
```



