---
title: "Untitled"
author: "yogesh sahu"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(dplyr)
library(readr)
CryptoMasterFile <- read_csv("returns_crypto.csv")
#View(CryptoMasterFile)


df<-CryptoMasterFile
#df<- df%>% rename (ticker=symbol)

library(dplyr)

# Assuming your data frame 'df' has a 'date' column in a recognizable date format
# Ensure 'date' is in the correct Date format
df$date <- as.Date(df$date, format = "%d/%m/%Y")

# Filter out rows where the date is on or before December 31, 2015
df <- df %>%
  filter(date > as.Date("2015-12-31"))

head(df)
df <- df %>%
  group_by(ticker) %>%
  mutate(
    `1d%` = round((close - lag(close)) / lag(close), 4)
  )
```




```{r}
library(dplyr)

# Assuming 'df' is your data frame and '1d%' is the column with daily returns
# Define the daily risk-free rate
risk_free_rate <- 0.02  # Adjust as per the current daily rate

# Calculate Sharpe Ratios
sharpe_ratios <- df %>%
  group_by(ticker) %>%
  summarise(
    average_return =round( mean(`1d%`, na.rm = TRUE),4),  # Calculate average daily return
    sd_return = round(sd(`1d%`, na.rm = TRUE),4),         # Calculate standard deviation of daily returns
    sharpe_ratio = round((average_return - risk_free_rate) / sd_return, 4)  # Calculate and round Sharpe Ratio to 4 decimal places
  ) %>%
  ungroup()

# View the results
head(sharpe_ratios)


```



```{r}
write.csv(sharpe_ratios, file = "sharpe_ratio.csv", row.names = FALSE)
```
```{r}

```

